version: '3.6'

networks:
  test:

volumes:
  db_data:

services:
  postgres:
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_MULTIPLE_DATABASES: parent,child
      POSTGRES_PASSWORD: postgrespassword
      TIMESCALEDB_TELEMETRY: "off"
    networks:
      - test
    ports:
    - "5432:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./pg-init-scripts:/docker-entrypoint-initdb.d

  hasura-parent:
    image: hasura/graphql-engine:v1.3.0-beta.1.cli-migrations-v2
    depends_on:
    - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/parent
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    networks:
      - test
    ports:
    - "8080:8080"
    restart: always
    volumes:
      - ./hasura-parent/migrations:/hasura-migrations
      - ./hasura-parent/metadata:/hasura-metadata

  hasura-child:
    image: hasura/graphql-engine:v1.3.0-beta.1.cli-migrations-v2
    depends_on:
    - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/child
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    networks:
      - test
    ports:
    - "8081:8080"
    restart: always
    volumes:
      - ./hasura-child/migrations:/hasura-migrations
      - ./hasura-child/metadata:/hasura-metadata